//! Standalone render of the three master_thesis flow figures (#408
//! verification). Renders fig07_01 (Provenance), fig06_01 (Quantum
//! pipeline), and fig09_01 (MAPE-K) to PNG so the adaptive col_gap +
//! grown box_h can be visually checked without rebuilding the full
//! book pipeline.

use agentic_figures::render_figspec;
use std::fs;
use std::path::PathBuf;

fn main() -> anyhow::Result<()> {
    let out_dir = PathBuf::from("target/flow_widen_samples");
    fs::create_dir_all(&out_dir)?;

    let fig07_01 = r#"{"id":"fig07_01","type":"flow","title":"The four regulatory threads as one compliance-by-construction pipeline","caption":"Provenance record feeding multi-BOM, CRA clock, sovereign attestation, and PQC gate","palette":"wong","data":{"nodes":["Multi-jurisdictional obligation set (CRA / DORA / AI Act / EO 14028 / FADP / CERT-In / PCI DSS)","Single provenance record (one build, one source of truth)","Unified multi-BOM (SBOM / CBOM / QBOM / AIBOM / HBOM)","ISO 5230 OpenChain license-compliance gate","CRA 24-hour vulnerability clock + VEX / SBOM-update service","Sovereign-build attestation (in-jurisdiction proof, HITL)","PQC deadline gate (NIST IR 8547 / CNSA 2.0)","Tiered compliance profile (financial / enterprise / community)","Proven-compliant Photon OS release"],"edges":[["Multi-jurisdictional obligation set (CRA / DORA / AI Act / EO 14028 / FADP / CERT-In / PCI DSS)","Single provenance record (one build, one source of truth)","convergence, not parallel inventories"],["Single provenance record (one build, one source of truth)","Unified multi-BOM (SBOM / CBOM / QBOM / AIBOM / HBOM)","emit once"],["Unified multi-BOM (SBOM / CBOM / QBOM / AIBOM / HBOM)","ISO 5230 OpenChain license-compliance gate","license fields require an auditable process"],["Unified multi-BOM (SBOM / CBOM / QBOM / AIBOM / HBOM)","CRA 24-hour vulnerability clock + VEX / SBOM-update service","BOM stays current for the support lifetime"],["Unified multi-BOM (SBOM / CBOM / QBOM / AIBOM / HBOM)","PQC deadline gate (NIST IR 8547 / CNSA 2.0)","QBOM / CBOM make the crypto inventory auditable"],["Single provenance record (one build, one source of truth)","Sovereign-build attestation (in-jurisdiction proof, HITL)","names build site + custody"],["Tiered compliance profile (financial / enterprise / community)","Proven-compliant Photon OS release","proportional obligation depth per deployment"],["ISO 5230 OpenChain license-compliance gate","Proven-compliant Photon OS release","BLOCK on incompatible license mix"],["CRA 24-hour vulnerability clock + VEX / SBOM-update service","Proven-compliant Photon OS release","living disclosure feed"],["Sovereign-build attestation (in-jurisdiction proof, HITL)","Proven-compliant Photon OS release","verifiable by the customer's auditor"],["PQC deadline gate (NIST IR 8547 / CNSA 2.0)","Proven-compliant Photon OS release","deprecated primitive fails the gate"]]}}"#;

    let fig06_01 = r#"{"id":"fig06_01","type":"flow","title":"The three quantum threads as one time-bounded governance pipeline","caption":"Quantum-pipeline flow from CRQC deadline through PQC, QUBO, and reproducible builds","palette":"wong","data":{"nodes":["CRQC arrival (2030-2035 est.)","Mosca deadline (CRQC - record_life - migrate)","CBOM crypto inventory","PQC migration (ML-KEM / ML-DSA / SLH-DSA)","eFuse / HABv4 hardware trap (HITL)","QUBO dependency optimisation (adaptive solver)","Reproducible quantum-build gate","Trustworthy autonomous builder"],"edges":[["CRQC arrival (2030-2035 est.)","Mosca deadline (CRQC - record_life - migrate)","sets the clock"],["Mosca deadline (CRQC - record_life - migrate)","CBOM crypto inventory","requires inventory first"],["CBOM crypto inventory","PQC migration (ML-KEM / ML-DSA / SLH-DSA)","migrate what is inventoried"],["PQC migration (ML-KEM / ML-DSA / SLH-DSA)","eFuse / HABv4 hardware trap (HITL)","embedded keys cannot migrate in place"],["QUBO dependency optimisation (adaptive solver)","Trustworthy autonomous builder","optimises the 1,000+ pkg graph"],["Reproducible quantum-build gate","Trustworthy autonomous builder","verifies transpiled circuits"],["PQC migration (ML-KEM / ML-DSA / SLH-DSA)","Trustworthy autonomous builder","PQC-signed artefacts"]]}}"#;

    let fig09_01 = r#"{"id":"fig09_01","type":"flow","title":"MAPE-K plus a harness-engineering gate, applied to the Photon OS builder","caption":"MAPE-K with harness gate after Plan and per-stage autonomy gating","palette":"wong","data":{"nodes":["Monitor (eBPF / BPF_LSM telemetry + CVE feed) -- L4 candidate","Analyse (agent triage, provenance-bound) -- L3 with provenance","Plan (QUBO dependency optimisation + finite-budget delta triage) -- L2 human-reviewed","Harness (sandbox + test harness validates plan; Fowler 2026, Lopopolo 2026) -- L2 gate","Execute (build / patch action; reversible vs irreversible split) -- L2/L1/L0","Knowledge (shared store; generative replay preserves it across OS versions)"],"edges":[["Monitor (eBPF / BPF_LSM telemetry + CVE feed) -- L4 candidate","Analyse (agent triage, provenance-bound) -- L3 with provenance","observed signals"],["Analyse (agent triage, provenance-bound) -- L3 with provenance","Plan (QUBO dependency optimisation + finite-budget delta triage) -- L2 human-reviewed","diagnosed gap"],["Plan (QUBO dependency optimisation + finite-budget delta triage) -- L2 human-reviewed","Harness (sandbox + test harness validates plan; Fowler 2026, Lopopolo 2026) -- L2 gate","proposed adaptation"],["Harness (sandbox + test harness validates plan; Fowler 2026, Lopopolo 2026) -- L2 gate","Execute (build / patch action; reversible vs irreversible split) -- L2/L1/L0","validated adaptation"],["Execute (build / patch action; reversible vs irreversible split) -- L2/L1/L0","Monitor (eBPF / BPF_LSM telemetry + CVE feed) -- L4 candidate","effect re-observed (loop closes)"],["Knowledge (shared store; generative replay preserves it across OS versions)","Analyse (agent triage, provenance-bound) -- L3 with provenance","shared context"],["Knowledge (shared store; generative replay preserves it across OS versions)","Plan (QUBO dependency optimisation + finite-budget delta triage) -- L2 human-reviewed","shared context"],["Knowledge (shared store; generative replay preserves it across OS versions)","Harness (sandbox + test harness validates plan; Fowler 2026, Lopopolo 2026) -- L2 gate","shared context"],["Execute (build / patch action; reversible vs irreversible split) -- L2/L1/L0","Knowledge (shared store; generative replay preserves it across OS versions)","outcome recorded"]]}}"#;

    for (id, spec) in [
        ("fig07_01", fig07_01),
        ("fig06_01", fig06_01),
        ("fig09_01", fig09_01),
    ] {
        let p = out_dir.join(format!("{id}.png"));
        render_figspec(spec, &p)?;
        let len = fs::metadata(&p)?.len();
        println!("wrote {} ({} bytes)", p.display(), len);
    }
    Ok(())
}
